### ISSUE TITLE
Recipe misses M1 architecture

### ISSUE THREAD

**Issue by tomschlenkhoff** [stripe/homebrew-stripe-cli#1]
Problem: Installing stripe-cli with homebrew on macOS on M1 architecture fails, as there is no install URL available.

Probable problem:  "if OS.mac? && Hardware::CPU.intel?"

Error message after update to 1.5.10: "Error: formulae require at least a URL"

**Comment by tomelm** [comment]
Sorry about that! Opened a PR to fix that here: https://github.com/stripe/stripe-cli/pull/608.

I'll try to get that merged on Monday!
