### ISSUE TITLE
Warning: Calling bottle :unneeded is deprecated! There is no replacement.

### ISSUE THREAD

**Issue by thepeoplesbourgeois** [stripe/homebrew-stripe-cli#3]
Removing the call and submitting a PR

**Comment by suz-stripe** [comment]
For tracking purposes: still waiting on the [Goreleaser Github Action](https://github.com/goreleaser/goreleaser-action) to be updated with the latest version of Goreleaser which contains the fix.

**Comment by remyleone** [comment]
https://github.com/stripe/homebrew-stripe-cli/pull/5

**Comment by pepin-stripe** [comment]
this is getting fixed here: https://github.com/stripe/stripe-cli/pull/785

**Comment by tomer-stripe** [comment]
Closing as pepin's fix should be in!
